grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: SGDRegressor
    module: sklearn.linear_model
    params:
      alpha: 0.001
      eta0: 0.01
      max_iter: 1
    search_param_grid:
      alpha:
      - 0.001
      - 0.0001
      - 0.005
      - 0.0005
      eta0:
      - 0.01
      - 0.05
      - 0.001
      max_iter:
      - 1
      - 3
      - 5

      
  module_1:
    class: PassiveAggressiveRegressor
    module: sklearn.linear_model
    params:
      C: 1.0
      loss: epsilon_insensitive
      max_iter: 1
    search_param_grid:
      C:
      - 1.0
      - 1.5
      - 2.0
      loss:
      - epsilon_insensitive
      - squared_epsilon_insensitive
      max_iter:
      - 1
      - 3
      - 5