columns:
  - vendorid: float
  - tpep_pickup_datetime: category
  - tpep_dropoff_datetime: category
  - passenger_count: float
  - trip_distance: float
  - ratecodeid: float
  - store_and_fwd_flag: category
  - pulocationid: float
  - dolocationid: float
  - payment_type: float
  - fare_amount: float
  - extra: float
  - mta_tax: float
  - tip_amount: float
  - tolls_amount: float
  - improvement_surcharge: float
  - total_amount: float
  - congestion_surcharge: float

numerical_columns:
  - vendorid
  - passenger_count
  - trip_distance
  - ratecodeid
  - pulocationid
  - dolocationid
  - payment_type
  - fare_amount
  - extra
  - mta_tax
  - tip_amount
  - tolls_amount
  - improvement_surcharge
  - total_amount
  - congestion_surcharge

categorical_columns:
  - tpep_pickup_datetime
  - tpep_dropoff_datetime
  - store_and_fwd_flag


drop_columns:
  - case_id
  - yr_of_estab